### ISSUE TITLE
sync-labels crashes with little debugging script

### ISSUE THREAD

**Issue by jesseclay** [ipfs/team-mgmt#780]
Running [sync-labels](https://github.com/ipfs/team-mgmt/blob/be9ee004d9b0a206c807f4072b00b459be931053/tools/sync-labels/readme.md) on a github organization with 100+ repositories crashes, with little feedback as to why. I have a feeling it's something to do with write permissions on a few of the repositories, or a repository name is off. Would be great to have this updated to:

- better report which repository(ies) didn't work
- continue updating repositories that do work

Right now when it crashes it does not update any repository.

**Comment by jesseclay** [comment]
and the generic error:

```
> github-sync-labels-milestones -t $GITHUB_AUTH_TOKEN -c config.json --verbose

read ECONNRESET
Error: read ECONNRESET
    at module.exports.sendError (/Users/hamilton/protocol/IT/ipfs-team-mgmt/tools/sync-labels/node_modules/github/lib/index.js:783:19)
    at /Users/hamilton/protocol/IT/ipfs-team-mgmt/tools/sync-labels/node_modules/github/lib/index.js:792:29
    at callCallback (/Users/hamilton/protocol/IT/ipfs-team-mgmt/tools/sync-labels/node_modules/github/lib/index.js:667:17)
    at ClientRequest.<anonymous> (/Users/hamilton/protocol/IT/ipfs-team-mgmt/tools/sync-labels/node_modules/github/lib/index.js:739:17)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sync-tool-labels@1.0.0 set-labels: `github-sync-labels-milestones -t $GITHUB_AUTH_TOKEN -c config.json --verbose`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sync-tool-labels@1.0.0 set-labels script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hamilton/.npm/_logs/2018-11-28T18_59_31_515Z-debug.log
```

**Comment by daviddias** [comment]
@victorb any update on this one?

**Comment by daviddias** [comment]
@jesseclay I went and did an update and ran it for a bunch of repos, so far success but I did get some hiccups that I documented at https://github.com/ipfs/team-mgmt/tree/master/tools/sync-labels#known-issues

**Comment by daviddias** [comment]
Closing this one for now.
